name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Archive production artifacts
      run: zip -r build.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SoccerForChangeBackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: build.zip
